# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath E:/altera/13.0sp1
set_param simulator.questaInstallPath C:/questasim64_10.6c
set_msg_config  -ruleid {1}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[63]}}  -suppress 
set_msg_config  -ruleid {10}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[16]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {100}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[55]}}  -suppress 
set_msg_config  -ruleid {101}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[54]}}  -suppress 
set_msg_config  -ruleid {102}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[53]}}  -suppress 
set_msg_config  -ruleid {103}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[52]}}  -suppress 
set_msg_config  -ruleid {104}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[51]}}  -suppress 
set_msg_config  -ruleid {105}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[50]}}  -suppress 
set_msg_config  -ruleid {106}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[49]}}  -suppress 
set_msg_config  -ruleid {107}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[48]}}  -suppress 
set_msg_config  -ruleid {108}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[47]}}  -suppress 
set_msg_config  -ruleid {109}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[46]}}  -suppress 
set_msg_config  -ruleid {11}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[42]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {110}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[45]}}  -suppress 
set_msg_config  -ruleid {111}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[44]}}  -suppress 
set_msg_config  -ruleid {112}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[43]}}  -suppress 
set_msg_config  -ruleid {113}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[42]}}  -suppress 
set_msg_config  -ruleid {114}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[41]}}  -suppress 
set_msg_config  -ruleid {115}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[40]}}  -suppress 
set_msg_config  -ruleid {116}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[39]}}  -suppress 
set_msg_config  -ruleid {117}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[38]}}  -suppress 
set_msg_config  -ruleid {118}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[37]}}  -suppress 
set_msg_config  -ruleid {119}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[36]}}  -suppress 
set_msg_config  -ruleid {12}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[15]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {120}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[35]}}  -suppress 
set_msg_config  -ruleid {121}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[34]}}  -suppress 
set_msg_config  -ruleid {122}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[33]}}  -suppress 
set_msg_config  -ruleid {123}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[32]}}  -suppress 
set_msg_config  -ruleid {124}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[31]}}  -suppress 
set_msg_config  -ruleid {125}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[30]}}  -suppress 
set_msg_config  -ruleid {126}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[29]}}  -suppress 
set_msg_config  -ruleid {127}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[28]}}  -suppress 
set_msg_config  -ruleid {128}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[27]}}  -suppress 
set_msg_config  -ruleid {129}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[26]}}  -suppress 
set_msg_config  -ruleid {13}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[7]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {130}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[25]}}  -suppress 
set_msg_config  -ruleid {131}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[24]}}  -suppress 
set_msg_config  -ruleid {132}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[23]}}  -suppress 
set_msg_config  -ruleid {133}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[22]}}  -suppress 
set_msg_config  -ruleid {134}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[21]}}  -suppress 
set_msg_config  -ruleid {135}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[20]}}  -suppress 
set_msg_config  -ruleid {136}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[19]}}  -suppress 
set_msg_config  -ruleid {137}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[18]}}  -suppress 
set_msg_config  -ruleid {138}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[17]}}  -suppress 
set_msg_config  -ruleid {139}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[16]}}  -suppress 
set_msg_config  -ruleid {14}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[36]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {140}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[15]}}  -suppress 
set_msg_config  -ruleid {141}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[14]}}  -suppress 
set_msg_config  -ruleid {142}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[63]}}  -suppress 
set_msg_config  -ruleid {143}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[62]}}  -suppress 
set_msg_config  -ruleid {144}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[61]}}  -suppress 
set_msg_config  -ruleid {145}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[60]}}  -suppress 
set_msg_config  -ruleid {146}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[59]}}  -suppress 
set_msg_config  -ruleid {147}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[58]}}  -suppress 
set_msg_config  -ruleid {148}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[57]}}  -suppress 
set_msg_config  -ruleid {149}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[56]}}  -suppress 
set_msg_config  -ruleid {15}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[38]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {150}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[55]}}  -suppress 
set_msg_config  -ruleid {151}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[54]}}  -suppress 
set_msg_config  -ruleid {152}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[53]}}  -suppress 
set_msg_config  -ruleid {153}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[52]}}  -suppress 
set_msg_config  -ruleid {154}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[51]}}  -suppress 
set_msg_config  -ruleid {155}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[50]}}  -suppress 
set_msg_config  -ruleid {156}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[49]}}  -suppress 
set_msg_config  -ruleid {157}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[48]}}  -suppress 
set_msg_config  -ruleid {158}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[47]}}  -suppress 
set_msg_config  -ruleid {159}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[46]}}  -suppress 
set_msg_config  -ruleid {16}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[29]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {160}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[45]}}  -suppress 
set_msg_config  -ruleid {161}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[44]}}  -suppress 
set_msg_config  -ruleid {162}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[43]}}  -suppress 
set_msg_config  -ruleid {163}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[42]}}  -suppress 
set_msg_config  -ruleid {164}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[41]}}  -suppress 
set_msg_config  -ruleid {165}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[40]}}  -suppress 
set_msg_config  -ruleid {166}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[39]}}  -suppress 
set_msg_config  -ruleid {167}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[38]}}  -suppress 
set_msg_config  -ruleid {168}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[37]}}  -suppress 
set_msg_config  -ruleid {169}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[36]}}  -suppress 
set_msg_config  -ruleid {17}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[46]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {170}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[35]}}  -suppress 
set_msg_config  -ruleid {171}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[34]}}  -suppress 
set_msg_config  -ruleid {172}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[33]}}  -suppress 
set_msg_config  -ruleid {173}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[32]}}  -suppress 
set_msg_config  -ruleid {174}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[31]}}  -suppress 
set_msg_config  -ruleid {175}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[30]}}  -suppress 
set_msg_config  -ruleid {176}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[29]}}  -suppress 
set_msg_config  -ruleid {177}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[28]}}  -suppress 
set_msg_config  -ruleid {178}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[27]}}  -suppress 
set_msg_config  -ruleid {179}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[26]}}  -suppress 
set_msg_config  -ruleid {18}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[2]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {180}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[25]}}  -suppress 
set_msg_config  -ruleid {181}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[24]}}  -suppress 
set_msg_config  -ruleid {182}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[23]}}  -suppress 
set_msg_config  -ruleid {183}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[22]}}  -suppress 
set_msg_config  -ruleid {184}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[21]}}  -suppress 
set_msg_config  -ruleid {185}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[20]}}  -suppress 
set_msg_config  -ruleid {186}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[19]}}  -suppress 
set_msg_config  -ruleid {187}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[18]}}  -suppress 
set_msg_config  -ruleid {188}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[17]}}  -suppress 
set_msg_config  -ruleid {189}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[16]}}  -suppress 
set_msg_config  -ruleid {19}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[50]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {190}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[15]}}  -suppress 
set_msg_config  -ruleid {191}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_memext has unconnected port i_riscv_memext_addr[14]}}  -suppress 
set_msg_config  -ruleid {192}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_em_dcache_addr_reg[63]) is unused and will be removed from module riscv_ppreg_em.}}  -suppress 
set_msg_config  -ruleid {193}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_em_rddata_sc_m_reg[1]) is unused and will be removed from module riscv_ppreg_em.}}  -suppress 
set_msg_config  -ruleid {194}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_em_dcache_addr_reg[62]) is unused and will be removed from module riscv_ppreg_em.}}  -suppress 
set_msg_config  -ruleid {195}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_de_amo_op_e_reg[1]) is unused and will be removed from module riscv_ppreg_de.}}  -suppress 
set_msg_config  -ruleid {196}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_em_dcache_addr_reg[61]) is unused and will be removed from module riscv_ppreg_em.}}  -suppress 
set_msg_config  -ruleid {197}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_em_dcache_addr_reg[60]) is unused and will be removed from module riscv_ppreg_em.}}  -suppress 
set_msg_config  -ruleid {198}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_em_dcache_addr_reg[59]) is unused and will be removed from module riscv_ppreg_em.}}  -suppress 
set_msg_config  -ruleid {199}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_em_dcache_addr_reg[58]) is unused and will be removed from module riscv_ppreg_em.}}  -suppress 
set_msg_config  -ruleid {2}  -id {Synth 8-4767}  -string {{WARNING: [Synth 8-4767] Trying to implement RAM 'valid_buffer_reg' in registers. Block RAM or DRAM implementation is not possible; see log for reasons.}}  -suppress 
set_msg_config  -ruleid {20}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[14]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {200}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_em_dcache_addr_reg[57]) is unused and will be removed from module riscv_ppreg_em.}}  -suppress 
set_msg_config  -ruleid {201}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_em_dcache_addr_reg[55]) is unused and will be removed from module riscv_ppreg_em.}}  -suppress 
set_msg_config  -ruleid {202}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_em_dcache_addr_reg[54]) is unused and will be removed from module riscv_ppreg_em.}}  -suppress 
set_msg_config  -ruleid {203}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_em_dcache_addr_reg[56]) is unused and will be removed from module riscv_ppreg_em.}}  -suppress 
set_msg_config  -ruleid {204}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_em_dcache_addr_reg[53]) is unused and will be removed from module riscv_ppreg_em.}}  -suppress 
set_msg_config  -ruleid {205}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_em_dcache_addr_reg[51]) is unused and will be removed from module riscv_ppreg_em.}}  -suppress 
set_msg_config  -ruleid {206}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_em_dcache_addr_reg[50]) is unused and will be removed from module riscv_ppreg_em.}}  -suppress 
set_msg_config  -ruleid {207}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_em_dcache_addr_reg[52]) is unused and will be removed from module riscv_ppreg_em.}}  -suppress 
set_msg_config  -ruleid {208}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_em_dcache_addr_reg[49]) is unused and will be removed from module riscv_ppreg_em.}}  -suppress 
set_msg_config  -ruleid {21}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[9]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {22}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[44]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {23}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[3]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {24}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[17]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {25}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[47]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {26}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[10]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {27}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[11]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {28}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[48]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {29}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[5]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {3}  -id {Synth 8-4446}  -string {{WARNING: [Synth 8-4446] all outputs are unconnected for this instance and logic may be removed [D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_datapath.sv:706]}}  -suppress 
set_msg_config  -ruleid {30}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[45]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {31}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[54]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {32}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[12]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {33}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[49]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {34}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[23]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {35}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[4]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {36}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[28]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {37}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[35]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {38}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[41]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {39}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[25]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {4}  -id {Synth 8-4767}  -string {{WARNING: [Synth 8-4767] Trying to implement RAM 'tag_buffer_reg' in registers. Block RAM or DRAM implementation is not possible; see log for reasons.}}  -suppress 
set_msg_config  -ruleid {40}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[18]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {41}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[39]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {42}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[27]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {43}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[40]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {44}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[34]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {45}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[13]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {46}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[31]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {47}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[6]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {48}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[26]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {49}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[21]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {5}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[62]}}  -suppress 
set_msg_config  -ruleid {50}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[22]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {51}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[24]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {52}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[8]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {53}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[20]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {54}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[43]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {55}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[33]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {56}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[32]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {57}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[30]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {58}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[37]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {59}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[19]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {6}  -id {Constraints 18-5210}  -string {{WARNING: [Constraints 18-5210] No constraint will be written out.}}  -suppress 
set_msg_config  -ruleid {60}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[1]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {61}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[51]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {62}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[52]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {63}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[53]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {64}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[57]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {65}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[55]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {66}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[56]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {67}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[58]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {68}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[59]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {69}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[60]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {7}  -id {Synth 8-6014}  -string {{WARNING: [Synth 8-6014] Unused sequential element valid_reg was removed.  [D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_multiplier.sv:62]}}  -suppress 
set_msg_config  -ruleid {70}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[61]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {71}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[62]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {72}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_em_rddata_sc_m_reg[63]) is unused and will be removed from module riscv_ppreg_em.}}  -suppress 
set_msg_config  -ruleid {73}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_mw_rddata_sc_wb_reg[63]) is unused and will be removed from module riscv_ppreg_mw.}}  -suppress 
set_msg_config  -ruleid {74}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (byte12_out_reg[1]) is unused and will be removed from module riscv_iram_data.}}  -suppress 
set_msg_config  -ruleid {75}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (stvec_reg[mode][1]) is unused and will be removed from module riscv_csrfile.}}  -suppress 
set_msg_config  -ruleid {76}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (byte14_out_reg[3]) is unused and will be removed from module riscv_iram_data.}}  -suppress 
set_msg_config  -ruleid {77}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (mtvec_reg[mode][1]) is unused and will be removed from module riscv_csrfile.}}  -suppress 
set_msg_config  -ruleid {78}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (medeleg_reg[10]) is unused and will be removed from module riscv_csrfile.}}  -suppress 
set_msg_config  -ruleid {79}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (mideleg_reg[0]) is unused and will be removed from module riscv_csrfile.}}  -suppress 
set_msg_config  -ruleid {8}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (z_reg[0]) is unused and will be removed from module riscv_multiplier.}}  -suppress 
set_msg_config  -ruleid {80}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (mideleg_reg[1]) is unused and will be removed from module riscv_csrfile.}}  -suppress 
set_msg_config  -ruleid {81}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (mideleg_reg[3]) is unused and will be removed from module riscv_csrfile.}}  -suppress 
set_msg_config  -ruleid {82}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (mideleg_reg[2]) is unused and will be removed from module riscv_csrfile.}}  -suppress 
set_msg_config  -ruleid {83}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (mideleg_reg[6]) is unused and will be removed from module riscv_csrfile.}}  -suppress 
set_msg_config  -ruleid {84}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (mideleg_reg[4]) is unused and will be removed from module riscv_csrfile.}}  -suppress 
set_msg_config  -ruleid {85}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (mideleg_reg[10]) is unused and will be removed from module riscv_csrfile.}}  -suppress 
set_msg_config  -ruleid {86}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (mideleg_reg[8]) is unused and will be removed from module riscv_csrfile.}}  -suppress 
set_msg_config  -ruleid {87}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (mideleg_reg[12]) is unused and will be removed from module riscv_csrfile.}}  -suppress 
set_msg_config  -ruleid {88}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (mideleg_reg[13]) is unused and will be removed from module riscv_csrfile.}}  -suppress 
set_msg_config  -ruleid {89}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (mideleg_reg[14]) is unused and will be removed from module riscv_csrfile.}}  -suppress 
set_msg_config  -ruleid {9}  -id {Synth 8-6014}  -string {{WARNING: [Synth 8-6014] Unused sequential element o_riscv_div_valid_reg was removed.  [D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_divider.sv:253]}}  -suppress 
set_msg_config  -ruleid {90}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (mideleg_reg[15]) is unused and will be removed from module riscv_csrfile.}}  -suppress 
set_msg_config  -ruleid {91}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_em_load_addr_misaligned_m_reg) is unused and will be removed from module riscv_ppreg_em.}}  -suppress 
set_msg_config  -ruleid {92}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_em_amo_op_m_reg[1]) is unused and will be removed from module riscv_ppreg_em.}}  -suppress 
set_msg_config  -ruleid {93}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (o_riscv_de_immzeroextend_e_reg[63]) is unused and will be removed from module riscv_ppreg_de.}}  -suppress 
set_msg_config  -ruleid {94}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[61]}}  -suppress 
set_msg_config  -ruleid {95}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[60]}}  -suppress 
set_msg_config  -ruleid {96}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[59]}}  -suppress 
set_msg_config  -ruleid {97}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[58]}}  -suppress 
set_msg_config  -ruleid {98}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[57]}}  -suppress 
set_msg_config  -ruleid {99}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design riscv_instructions_cache has unconnected port i_riscv_icache_phys_addr[56]}}  -suppress 
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {D:/RISC-V/RTL Design/Synthesis/syn.cache/wt} [current_project]
set_property parent.project_path {D:/RISC-V/RTL Design/Synthesis/syn.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/RISC-V/RTL Design/Synthesis/syn.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_ICU.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_alu.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_branch.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_button_debouncer.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_button_debouncer_delayed.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_button_debouncer_fsm.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_compressed_decoder.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_control_unit.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_core.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_counter.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_csrfile.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_datapath.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_dcache_amo.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_dcache_data.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_dcache_fsm.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_dcache_tag.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_dcache_top.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_debouncer_timer.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_decode_stage.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_divider.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_dram_counter.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_dram_data.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_dram_model.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_execute_stage.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_extend.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_fetch_stage.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_hazardunit.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_icache_fsm.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_icache_inst.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_icache_tag.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_icache_top.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_iram_counter.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_iram_data.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_iram_model.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_lsu.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_mem_stage.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_memext.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_misalignment_unit.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_multiplier.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_mux2.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_mux3.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_mux4.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_mux5.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_pc.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_pcadder.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_ppreg_de.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_ppreg_em.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_ppreg_fd.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_ppreg_mw.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_rf.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_rst_sync.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_timer_irq.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_trap_wb.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_wb_stage.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_zeroextend.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/uart_clk_div.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/uart_fifo_df_sync.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/uart_fifo_gray_conv.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/uart_fifo_mem_ctrl.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/uart_fifo_rd.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/uart_fifo_top.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/uart_fifo_wr.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/uart_peripheral_top.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/uart_pulse_gen.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/uart_tx_fsm.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/uart_tx_mux.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/uart_tx_parity_calc.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/uart_tx_serializer.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/uart_tx_top.sv}
  {D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/riscv_top.sv}
}
read_ip -quiet {{D:/RISC-V/RTL Design/Synthesis/syn.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci}}
set_property used_in_implementation false [get_files -all {{d:/RISC-V/RTL Design/Synthesis/syn.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/RISC-V/RTL Design/Synthesis/syn.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/RISC-V/RTL Design/Synthesis/syn.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/pre_syn_cons.xdc}}
set_property used_in_implementation false [get_files {{D:/RISC-V/RTL Design/GP-RV64IMAC/RV64IMAC_M_S_Modes_UART_TX/pre_syn_cons.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top riscv_top -part xc7a35tcpg236-1 -flatten_hierarchy none


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef riscv_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file riscv_top_utilization_synth.rpt -pb riscv_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
